### ISSUE TITLE
Invalid number format in timeseries json

### ISSUE THREAD

**Issue by ezwelty** [gadomski/cwms-jsonapi#3]
Currently, `timeseriesdata.value` has values like:

- ".0123"
- "-.0123"

However, to be valid JSON, these need to include the "0" before the period:

- "0.0123"
- "-0.0123"

You can see for yourself using [jsonlint](http://jsonlint.com/).

**Comment by gadomski** [comment]
Yup, you're correct. I'm currently tracking down the login information for the database so I can get back in an update. Thanks for the report.
