### ISSUE TITLE
Suspect values in quality_code

### ISSUE THREAD

**Issue by ezwelty** [gadomski/cwms-jsonapi#7]
All quality codes for Columbia Glacier (COL) are 0, except Relative humidity (15110021), Pressure (15115021), and Voltage (15116021) all have many instances of these two strange values:

* 2147486339
* 2147488643

For example: https://reservoircontrol.usace.army.mil/NE/pls/cwmsweb/cwms_web.jsonapi.timeseriesdata?ts_codes=15110021&summary_interval=monthly

If not a bug, what do these mean?

**Comment by gadomski** [comment]
Those look a lot like signed integers that have been interpreted as positive integers, but I don't know that for sure. I've asked a source for information (/documentation) for the quality code field, and will report back when I get answers.

At https://github.com/gadomski/cwms-jsonapi/blob/master/JSONAPI.sql#L303 I pluck the maximum quality code value as the quality code for the aggregate number, which is both conservative and naive. A smarter approach would be to filter non-zero quality codes before aggregation, assuming of course that a zero quality code is A Good Thing. That approach would be considered an enhancement and worthy of it's own issue (#8).

**Comment by gadomski** [comment]
I just heard back that the value is actually a bitmask, which explains the huge values. Keeping this open until I find out what that bitmask means.
